version: '3'

services:
  csis-db:
    image: postgres:alpine
    container_name: csis-db
    environment:
      - "POSTGRES_DB=csis_db_test"
    ports:
      - "5432:5432"
  csis-redis:
    container_name: csis-redis
    image: redis:alpine
    ports:
      - "6379:6379"
  csis-app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: csis-app
    command: "rails t"
    container_name: csis-app-test
    working_dir: /var/www/csis
    depends_on:
      - csis-db
      - csis-redis
    environment:
      - "RAILS_ENV=test"
      - "REDIS_URL=redis://csis-redis:6379"
      - "POSTGRES_HOST=csis-db"
      - "COVERAGE=true"
